"""Elastic / Kibana saved-objects NDJSON generator.

Emits one ``search`` saved object per panel plus a ``dashboard`` saved
object that references them via panelsJSON — importable through Kibana
Saved Objects. Best-effort layout; analysts get every panel as a saved
search wired into a dashboard grid.
"""

from __future__ import annotations

import json

from app.services.dashboard.builder import DashboardPlan, PanelSpec


def _slug(text: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in text.lower()).strip("-")[:80]


def _search_object(panel: PanelSpec, obj_id: str) -> dict:
    return {
        "id": obj_id,
        "type": "search",
        "attributes": {
            "title": panel.title,
            "description": f"MetaSec Security Center — {panel.technique or ''}",
            "hits": 0,
            "columns": ["_source"],
            "sort": [],
            "kibanaSavedObjectMeta": {
                "searchSourceJSON": json.dumps(
                    {"query": {"query": panel.query, "language": "kuery"}, "filter": []}
                )
            },
        },
        "references": [],
    }


def _dashboard_object(plan: DashboardPlan, panel_ids: list[str], dash_id: str) -> dict:
    panels_json = []
    references = []
    for idx, pid in enumerate(panel_ids):
        col = (idx % 2) * 24
        row = (idx // 2) * 15
        panel_ref = f"panel_{idx}"
        panels_json.append(
            {
                "version": "8.0.0",
                "gridData": {"x": col, "y": row, "w": 24, "h": 15, "i": panel_ref},
                "panelIndex": panel_ref,
                "embeddableConfig": {},
                "panelRefName": panel_ref,
            }
        )
        references.append({"name": f"{panel_ref}:panel_{panel_ref}", "type": "search", "id": pid})
    return {
        "id": dash_id,
        "type": "dashboard",
        "attributes": {
            "title": plan.name,
            "description": f"Generated by MetaSec Security Center — {plan.layout} layout.",
            "panelsJSON": json.dumps(panels_json),
            "optionsJSON": json.dumps({"useMargins": True, "hidePanelTitles": False}),
            "timeRestore": False,
            "kibanaSavedObjectMeta": {"searchSourceJSON": json.dumps({"query": {"query": "", "language": "kuery"}, "filter": []})},
        },
        "references": references,
    }


def generate(plan: DashboardPlan, rows: list[list[PanelSpec]]) -> str:
    base = _slug(plan.name) or "metasec-dashboard"
    lines: list[str] = []
    panel_ids: list[str] = []
    flat = [p for row in rows for p in row]
    for idx, panel in enumerate(flat):
        obj_id = f"tf-{base}-search-{idx}"
        panel_ids.append(obj_id)
        lines.append(json.dumps(_search_object(panel, obj_id)))
    lines.append(json.dumps(_dashboard_object(plan, panel_ids, f"tf-{base}-dashboard")))
    return "\n".join(lines)
