"""Microsoft Sentinel Workbook generator (rich)."""

from __future__ import annotations

import json

from app.services.dashboard.builder import DashboardPlan, PanelSpec


def _overview_md(plan: DashboardPlan) -> str:
    s = plan.summary
    sev = " · ".join(f"{k}: {v}" for k, v in sorted(s.severity_counts.items()))
    tops = "\n".join(f"- {t} — {c} detections" for t, c in s.top_techniques[:8])
    scope_bits = []
    if plan.scope.get("techniques"):
        scope_bits.append("Techniques: " + ", ".join(plan.scope["techniques"]))
    if plan.scope.get("tactics"):
        scope_bits.append("Tactics: " + ", ".join(plan.scope["tactics"]))
    return (
        f"# {plan.name}\n"
        f"_{' · '.join(scope_bits) or 'All detections'}_\n\n"
        f"**{s.detection_count}** detections · **{s.technique_count}** techniques · **{s.tactic_count}** tactics\n\n"
        f"Severity — {sev}\n\n"
        f"### Top techniques\n{tops}\n\n"
        f"> Generated by MetaSec Security Center — {plan.layout} layout"
    )


def _markdown_item(text: str, name: str) -> dict:
    return {"type": 1, "content": {"json": text}, "name": name}


def _query_item(panel: PanelSpec, name: str, viz: str) -> dict:
    return {
        "type": 3,
        "content": {
            "version": "KqlItem/1.0",
            "query": panel.query,
            "size": 0,
            "title": panel.title,
            "timeContext": {"durationMs": 86400000},
            "queryType": 0,
            "resourceType": "microsoft.operationalinsights/workspaces",
            "visualization": viz,
        },
        "name": name,
    }


def _trend_item(panel: PanelSpec, name: str) -> dict:
    # A bin/summarize trend layered on the detection query.
    q = f"{panel.query}\n| summarize Count = count() by bin(TimeGenerated, 1h)\n| render timechart"
    item = _query_item(panel, name, "timechart")
    item["content"]["query"] = q
    item["content"]["title"] = f"{panel.title} — trend"
    return item


def generate(plan: DashboardPlan, rows) -> str:
    ordered = [p for row in rows for p in row] if rows else plan.panels
    items: list[dict] = [_markdown_item(_overview_md(plan), "tf-overview")]
    for i, panel in enumerate(ordered):
        items.append(_markdown_item(f"## {panel.title}", f"tf-h-{i}"))
        items.append(_query_item(panel, f"tf-q-{i}", "table"))
        items.append(_trend_item(panel, f"tf-t-{i}"))
    workbook = {"version": "Notebook/1.0", "items": items, "isLocked": False, "fallbackResourceIds": []}
    return json.dumps(workbook, indent=2)
