"""Splunk Simple XML dashboard generator (rich)."""

from __future__ import annotations

from xml.sax.saxutils import escape

from app.services.dashboard.builder import DashboardPlan, PanelSpec

_SEV_COLOR = {"critical": "#dc4e41", "high": "#f1813f", "medium": "#f8be34", "low": "#6db7c6", "informational": "#708794"}


def _overview_html(plan: DashboardPlan) -> str:
    s = plan.summary
    sev = "".join(
        f'<span style="display:inline-block;margin:2px 10px 2px 0;padding:3px 10px;border-radius:10px;'
        f'background:{_SEV_COLOR.get(k, "#555")};color:#0b0e14;font-weight:600">{escape(k)}: {v}</span>'
        for k, v in sorted(s.severity_counts.items())
    )
    tops = "".join(f"<li>{escape(t)} — {c} detections</li>" for t, c in s.top_techniques[:8])
    scope_bits = []
    if plan.scope.get("techniques"):
        scope_bits.append("Techniques: " + ", ".join(plan.scope["techniques"]))
    if plan.scope.get("tactics"):
        scope_bits.append("Tactics: " + ", ".join(plan.scope["tactics"]))
    if plan.scope.get("severity"):
        scope_bits.append("Severity: " + plan.scope["severity"])
    scope_line = escape(" · ".join(scope_bits) or "All detections")
    return (
        "  <panel>\n    <html>\n"
        f'      <div style="padding:8px 4px">\n'
        f"        <h2>{escape(plan.name)}</h2>\n"
        f'        <p style="color:#9aa7bd">{scope_line}</p>\n'
        f'        <div style="display:flex;gap:24px;flex-wrap:wrap;margin:12px 0">\n'
        f'          <div><div style="font-size:28px;font-weight:700">{s.detection_count}</div><div style="color:#9aa7bd">detections</div></div>\n'
        f'          <div><div style="font-size:28px;font-weight:700">{s.technique_count}</div><div style="color:#9aa7bd">techniques</div></div>\n'
        f'          <div><div style="font-size:28px;font-weight:700">{s.tactic_count}</div><div style="color:#9aa7bd">tactics</div></div>\n'
        f"        </div>\n"
        f'        <div style="margin:8px 0">{sev}</div>\n'
        f"        <h4>Top techniques</h4>\n        <ul>{tops}</ul>\n"
        f'        <p style="color:#708794;font-size:12px">Generated by MetaSec Security Center — {escape(plan.layout)} layout</p>\n'
        f"      </div>\n    </html>\n  </panel>"
    )


def _detection_row(panel: PanelSpec) -> str:
    title = escape(panel.title)
    q = escape(panel.query)
    sev = (panel.severity or "medium").lower()
    color = _SEV_COLOR.get(sev, "#6db7c6")
    single = (
        f"  <panel>\n    <title>{title} — count</title>\n    <single>\n"
        f"      <search>\n        <query>{q} | stats count</query>\n"
        f"        <earliest>$time.earliest$</earliest>\n        <latest>$time.latest$</latest>\n      </search>\n"
        f'      <option name="colorBy">value</option>\n'
        f'      <option name="rangeColors">["{color}","{color}"]</option>\n'
        f'      <option name="drilldown">all</option>\n    </single>\n  </panel>'
    )
    trend = (
        f"  <panel>\n    <title>{title} — trend</title>\n    <chart>\n"
        f"      <search>\n        <query>{q} | timechart count</query>\n"
        f"        <earliest>$time.earliest$</earliest>\n        <latest>$time.latest$</latest>\n      </search>\n"
        f'      <option name="charting.chart">column</option>\n'
        f'      <option name="charting.legend.placement">none</option>\n    </chart>\n  </panel>'
    )
    entity = "src" if "src" in panel.query else ("user" if "user" in panel.query.lower() else "host")
    detail = (
        f"  <panel>\n    <title>{title} — top {entity}</title>\n    <table>\n"
        f"      <search>\n        <query>{q} | top limit=10 {entity}</query>\n"
        f"        <earliest>$time.earliest$</earliest>\n        <latest>$time.latest$</latest>\n      </search>\n"
        f'      <option name="drilldown">cell</option>\n    </table>\n  </panel>'
    )
    return "<row>\n" + "\n".join([single, trend, detail]) + "\n</row>"


def generate(plan: DashboardPlan, rows, earliest: str = "-24h", latest: str = "now") -> str:
    ordered = [p for row in rows for p in row] if rows else plan.panels
    parts = [
        '<form version="1.1" theme="dark">',
        f"  <label>{escape(plan.name)}</label>",
        f"  <description>MetaSec Security Center generated — {plan.summary.detection_count} detections, {plan.summary.technique_count} techniques.</description>",
        '  <fieldset submitButton="false" autoRun="true">',
        '    <input type="time" token="time">',
        "      <label>Time range</label>",
        "      <default>",
        f"        <earliest>{escape(earliest)}</earliest>",
        f"        <latest>{escape(latest)}</latest>",
        "      </default>",
        "    </input>",
        "  </fieldset>",
        "<row>",
        _overview_html(plan),
        "</row>",
    ]
    for panel in ordered:
        parts.append(_detection_row(panel))
    parts.append("</form>")
    return "\n".join(parts)
